{
 "title": "Web Application Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "FQDN",
    "label": "FQDN",
    "query": {
     "query": "label_values({job=\"HTTP-GET\"},FQDN)"
    }
   }
  ]
 },
 "panels": [
  { "title": "WEB SERVER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PING STATUS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"ICMP\",FQDN=~\"$FQDN\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "HTTP RESPONSE TIME",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_http_duration_seconds{FQDN=~\"$FQDN\",job=\"HTTP-GET\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "PUBLIC DNS PROPAGATION",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "probe_dns_query_succeeded{NS_TYPE=\"PUBLIC DNS\",job=~\"dns-against-$FQDN\"}"
    }
   ]
  },
  {
   "title": "PUBLIC DNS PROPAGATION (HISTORY)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "probe_dns_query_succeeded{NS_TYPE=\"PUBLIC DNS\",job=~\"dns-against-$FQDN\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP RESPONSE CODE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{FQDN=~\"$FQDN\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "UPTIME",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"ICMP\",FQDN=~\"$FQDN\"}",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "LOCAL DNS PROPAGATION",
   "type": "table",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 9 },
   "targets": [
    {
     "expr": "probe_dns_query_succeeded{NS_TYPE=\"LOCAL DNS\",job=~\"dns-against-$FQDN\"}"
    }
   ]
  },
  {
   "title": "LOCAL DNS PROPAGATION (HISTORY)",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 9 },
   "targets": [
    {
     "expr": "probe_dns_query_succeeded{NS_TYPE=\"LOCAL DNS\",job=~\"dns-against-$FQDN\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP VERSION",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_version{FQDN=~\"$FQDN\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PING STATUS HISTORY",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 12, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_success{job=\"ICMP\",FQDN=~\"$FQDN\"}",
     "legendFormat": "{{FQDN}}"
    }
   ]
  },
  {
   "title": "SSL CERTIFICATE EXPIRY",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{FQDN=~\"$FQDN\"}-time()"
    }
   ]
  }
 ]
}