apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  uid: prometheus-data-source
  url: http://prometheus:9090
  version: 1
  editable: true
